# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 01:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera', models.CharField(blank=True, choices=[('CA', 'Cannon'), ('NI', 'Nikon'), ('OL', 'Olympus'), ('SO', 'Sony'), ('PA', 'Panasonic'), ('PH', 'Phone')], max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('bio', models.CharField(blank=True, max_length=255, null=True)),
                ('website', models.CharField(blank=True, max_length=255)),
                ('hireable', models.BooleanField(default=True)),
                ('travel_radius', models.PositiveSmallIntegerField()),
                ('phone', models.CharField(max_length=12)),
                ('photo_type', models.CharField(blank=True, choices=[('LA', 'Landscape'), ('BW', 'Black and White'), ('PO', 'Portrait'), ('WE', 'Wedding'), ('SP', 'Sports'), ('WI', 'Wildlife'), ('UR', 'Urban'), ('TR', 'Travel')], max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
