# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='travel_radius',
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
