# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 03:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0002_auto_20170116_1803'),
        ('imager_profile', '0002_auto_20170116_1804'),
    ]

    operations = [
    ]
