# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 20:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0004_auto_20170117_1810'),
        ('imager_profile', '0004_auto_20170119_1120'),
    ]

    operations = [
    ]
