# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 06:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0005_merge_20170119_1241'),
        ('imager_profile', '0007_auto_20170124_1644'),
    ]

    operations = [
    ]
