# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='contents',
            field=models.ManyToManyField(blank=True, related_name='in_album', to='imager_images.Photo'),
        ),
    ]
