# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 00:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0004_auto_20170122_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cover', to='imager_images.Photo'),
        ),
        migrations.AlterField(
            model_name='album',
            name='date_modified',
            field=models.DateField(auto_now_add=True, default='01-24-2017'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='album',
            name='date_published',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2017, 1, 24, 16, 44, 29, 561654)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='album',
            name='published',
            field=models.CharField(blank=True, choices=[('PRIVATE', 'Private'), ('SHARED', 'Shared'), ('PUBLIC', 'Public'), ('', 'Select who can view')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='date_published',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2017, 1, 24, 16, 44, 56, 344508)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photo',
            name='published',
            field=models.CharField(blank=True, choices=[('PRIVATE', 'Private'), ('SHARED', 'Shared'), ('PUBLIC', 'Public'), ('', 'Select who can view')], max_length=255, null=True),
        ),
    ]
