# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 07:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0006_auto_20170124_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='imager_profile.UserProfile'),
        ),
        migrations.AlterField(
            model_name='album',
            name='published',
            field=models.CharField(choices=[('PRIVATE', 'Private'), ('SHARED', 'Shared'), ('PUBLIC', 'Public')], default='PUBLIC', max_length=255),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photographer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='imager_profile.UserProfile'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='published',
            field=models.CharField(choices=[('PRIVATE', 'Private'), ('SHARED', 'Shared'), ('PUBLIC', 'Public')], default='PUBLIC', max_length=255),
        ),
    ]
