# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 23:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0011_auto_20170201_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='tags',
        ),
    ]
