# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 23:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0013_auto_20170202_2218'),
        ('imager_images', '0010_auto_20170209_1103'),
    ]

    operations = [
    ]
